# Hospitality Business Intelligence & Revenue Analytics

## Exploratory Data Analysis (EDA)

### Objective

Analyze hotel booking patterns, cancellations, occupancy, revenue, and customer behavior to provide business recommendations.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use("ggplot")

pd.set_option("display.max_columns", None)

# Load Cleaned Dataset

In [4]:
df = pd.read_csv("../Data/cleaned/hotel_bookings_cleaned.csv")

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,0,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,0,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,0,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240,0,Transient,98.0,0,1,Check-Out,2015-07-03

# Feature Engineering

In [5]:
df["total_guests"] = (
    df["adults"] +
    df["children"] +
    df["babies"]
)

# Total Nights

In [6]:
df["total_nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

# Total Revenue

In [7]:
df["total_revenue"] = (
    df["adr"] *
    df["total_nights"]
)

# Executive KPI Summary

In [8]:
print("Total Bookings :", len(df))
print("Cancelled Bookings :", df["is_canceled"].sum())
print("Cancellation Rate :", round(df["is_canceled"].mean()*100,2),"%")
print("Average ADR :", round(df["adr"].mean(),2))
print("Estimated Revenue :", round(df["total_revenue"].sum(),2))

Total Bookings : 119390
Cancelled Bookings : 44224
Cancellation Rate : 37.04 %
Average ADR : 101.83
Estimated Revenue : 42723497.53

 # Business Question 1

 Which hotel generates the highest revenue ?

In [9]:
hotel_revenue = (
    df.groupby("hotel")["total_revenue"]
      .sum()
      .sort_values(ascending=False)
)

hotel_revenue

hotel
City Hotel      25279469.96
Resort Hotel    17444027.57
Name: total_revenue, dtype: float64

# Business Question 2

Which market segment generates the highest revenue ?

In [10]:
segment = (
    df.groupby("market_segment")
      .agg(
          Bookings=("hotel","count"),
          Revenue=("total_revenue","sum")
      )
      .sort_values(
          by="Revenue",
          ascending=False
      )
)

segment

                Bookings      Revenue
market_segment
Online TA          56477  23942047.53
Offline TA/TO      24219   8151912.73
Direct             12606   5093028.39
Groups             19811   4669636.74
Corporate           5295    774295.26
Aviation             237     87446.36
Complementary        743      5082.52
Undefined              2        48.00

# Business Question 3

Which countries generate the most bookings ?

In [11]:
country = (
    df["country"]
      .value_counts()
      .head(10)
)

country

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
ITA     3766
IRL     3375
BEL     2342
BRA     2224
NLD     2104
Name: count, dtype: int64

# Business Question 4

Which month receives the most bookings ?

In [12]:
month = (
    df["arrival_date_month"]
      .value_counts()
)

month

arrival_date_month
August       13877
July         12661
May          11791
October      11160
April        11089
June         10939
September    10508
March         9794
February      8068
November      6794
December      6780
January       5929
Name: count, dtype: int64

# Business Question 5

Cancellation Rate by Hotel

In [13]:
cancel = (
    df.groupby("hotel")["is_canceled"]
      .mean()*100
)

cancel

hotel
City Hotel      41.726963
Resort Hotel    27.763355
Name: is_canceled, dtype: float64

# Business Question 6

Average Stay Length

In [14]:
df["total_nights"].describe()

count    119390.000000
mean          3.427900
std           2.557439
min           0.000000
25%           2.000000
50%           3.000000
75%           4.000000
max          69.000000
Name: total_nights, dtype: float64

## Key Findings

### Revenue

- Highest revenue generated by ____________

### Cancellation

- Cancellation rate is ______ %

### Market Segment

- Highest performing segment is ___________

### Country

- Largest customer base comes from ___________

### Seasonality

- Peak booking month is ____________

### Recommendation

1.
2.
3.